! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


SUBROUTINE C_SLOPES(XTAB_DIM_1, XTAB, YTAB_DIM_1, YTAB, MTAB_DIM_1, MTAB, NUM) BIND(C)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: XTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(XTAB_DIM_1) :: XTAB
  INTEGER, INTENT(IN) :: YTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(YTAB_DIM_1) :: YTAB
  INTEGER, INTENT(IN) :: MTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(MTAB_DIM_1) :: MTAB
  INTEGER, INTENT(INOUT) :: NUM

  INTERFACE
    SUBROUTINE SLOPES(XTAB, YTAB, MTAB, NUM)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !                                       N.C.STATE UNIVERSITY
      !
      !
      ! SLOPES CALCULATES THE DERIVATIVE AT EACH OF THE DATA POINTS.  THE
      ! SLOPES PROVIDED WILL INSURE THAT AN OSCULATORY QUADRATIC SPLINE WILL
      ! HAVE ONE ADDITIONAL KNOT BETWEEN TWO ADJACENT POINTS OF INTERPOLATION.
      ! CONVEXITY AND MONOTONICITY ARE PRESERVED WHEREVER THESE CONDITIONS
      ! ARE COMPATIBLE WITH THE DATA.
      !
      ! ON INPUT--
      !
      !   XTAB CONTAINS THE ABSCISSAS OF THE DATA POINTS.
      !
      !   YTAB CONTAINS THE ORDINATES OF THE DATA POINTS.
      !
      !   NUM IS THE NUMBER OF DATA POINTS (DIMENSION OF XTAB,YTAB).
      !
      !
      ! ON OUTPUT--
      !
      !   MTAB CONTAINS THE VALUE OF THE FIRST DERIVATIVE AT EACH DATA POINT.
      !
      ! AND
      !
      !   SLOPES DOES NOT ALTER XTAB,YTAB,NUM.
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT), DIMENSION(NUM) :: XTAB
      REAL, INTENT(INOUT), DIMENSION(NUM) :: YTAB
      REAL, INTENT(INOUT), DIMENSION(NUM) :: MTAB
      INTEGER, INTENT(INOUT) :: NUM
    END SUBROUTINE SLOPES
  END INTERFACE

  CALL SLOPES(XTAB, YTAB, MTAB, NUM)
END SUBROUTINE C_SLOPES


SUBROUTINE C_MEVAL(XVAL_DIM_1, XVAL, YVAL_DIM_1, YVAL, XTAB_DIM_1, XTAB, YTAB_DIM_1, YTAB, MTAB_DIM_1, MTAB, NUM, NUME, EPS, ERR) B&
&IND(C)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: XVAL_DIM_1
  REAL, INTENT(INOUT), DIMENSION(XVAL_DIM_1) :: XVAL
  INTEGER, INTENT(IN) :: YVAL_DIM_1
  REAL, INTENT(INOUT), DIMENSION(YVAL_DIM_1) :: YVAL
  INTEGER, INTENT(IN) :: XTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(XTAB_DIM_1) :: XTAB
  INTEGER, INTENT(IN) :: YTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(YTAB_DIM_1) :: YTAB
  INTEGER, INTENT(IN) :: MTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(MTAB_DIM_1) :: MTAB
  INTEGER, INTENT(INOUT) :: NUM
  INTEGER, INTENT(INOUT) :: NUME
  REAL, INTENT(INOUT) :: EPS
  INTEGER, INTENT(INOUT) :: ERR

  INTERFACE
    SUBROUTINE MEVAL(XVAL, YVAL, XTAB, YTAB, MTAB, NUM, NUME, EPS, ERR)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !                                       N.C. STATE UNIVERSITY
      !
      !
      ! MEVAL CONTROLS THE EVALUATION OF AN OSCULATORY QUADRATIC SPLINE.  THE
      ! USER MAY PROVIDE HIS OWN SLOPES AT THE POINTS OF INTERPOLATION OR USE
      ! THE SUBROUTINE 'SLOPES' TO CALCULATE SLOPES WHICH ARE CONSISTENT WITH
      ! THE SHAPE OF THE DATA.
      !
      !
      !
      ! ON INPUT--
      !
      !   XVAL MUST BE A NONDECREASING VECTOR OF POINTS AT WHICH THE SPLINE
      !   WILL BE EVALUATED.
      !
      !   XTAB CONTAINS THE ABSCISSAS OF THE DATA POINTS TO BE INTERPOLATED.
      !   XTAB MUST BE INCREASING.
      !
      !   YTAB CONTAINS THE ORDINATES OF THE DATA POINTS TO BE INTERPOLATED.
      !
      !   MTAB CONTAINS THE SLOPE OF THE SPLINE AT EACH POINT OF INTERPOLA-
      !   TION.
      !
      !   NUM IS THE NUMBER OF DATA POINTS (DIMENSION OF XTAB AND YTAB).
      !
      !   NUME IS THE NUMBER OF POINTS OF EVALUATION (DIMENSION OF XVAL AND
      !   YVAL).
      !
      !   EPS IS A RELATIVE ERROR TOLERANCE USED IN SUBROUTINE 'CHOOSE'
      !   TO DISTINGUISH THE SITUATION MTAB(I) OR MTAB(I+1) IS RELATIVELY
      !   CLOSE TO THE SLOPE OR TWICE THE SLOPE OF THE LINEAR SEGMENT
      !   BETWEEN XTAB(I) AND XTAB(I+1).  IF THIS SITUATION OCCURS,
      !   ROUNDOFF MAY CAUSE A CHANGE IN CONVEXITY OR MONOTONICITY OF THE
      !   RESULTING SPLINE AND A CHANGE IN THE CASE NUMBER PROVIDED BY
      !   CHOOSE.  IF EPS IS NOT EQUAL TO ZERO, THEN EPS SHOULD BE GREATER
      !   THAN OR EQUAL TO MACHINE EPSILON.
      !
      !
      ! ON OUTPUT--
      !
      ! YVAL CONTAINS THE IMAGES OF THE POINTS IN XVAL.
      !
      !   ERR IS AN ERROR CODE--
      !      ERR=0 - MEVAL RAN NORMALLY.
      !      ERR=1 - XVAL(I) IS LESS THAN XTAB(1) FOR AT LEAST ONE I OR
      !              XVAL(I) IS GREATER THAN XTAB(NUM) FOR AT LEAST ONE I.
      !              MEVAL WILL EXTRAPOLATE TO PROVIDE FUNCTION VALUES FOR
      !              THESE ABSCISSAS.
      !      ERR=2 - XVAL(I+1) .LT. XVAL(I) FOR SOME I.
      !
      ! AND
      !
      !   MEVAL DOES NOT ALTER XVAL,XTAB,YTAB,MTAB,NUM,NUME.
      !
      !
      !   MEVAL CALLS THE FOLLOWING SUBROUTINES OR FUNCTIONS:
      !      SEARCH
      !      CASES
      !      CHOOSE
      !      SPLINE
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT), DIMENSION(NUME) :: XVAL
      REAL, INTENT(INOUT), DIMENSION(NUME) :: YVAL
      REAL, INTENT(INOUT), DIMENSION(NUM) :: XTAB
      REAL, INTENT(INOUT), DIMENSION(NUM) :: YTAB
      REAL, INTENT(INOUT), DIMENSION(NUM) :: MTAB
      INTEGER, INTENT(INOUT) :: NUM
      INTEGER, INTENT(INOUT) :: NUME
      REAL, INTENT(INOUT) :: EPS
      INTEGER, INTENT(INOUT) :: ERR
    END SUBROUTINE MEVAL
  END INTERFACE

  CALL MEVAL(XVAL, YVAL, XTAB, YTAB, MTAB, NUM, NUME, EPS, ERR)
END SUBROUTINE C_MEVAL


SUBROUTINE C_SEARCH(XTAB_DIM_1, XTAB, NUM, S, LCN, FND) BIND(C)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: XTAB_DIM_1
  REAL, INTENT(INOUT), DIMENSION(XTAB_DIM_1) :: XTAB
  INTEGER, INTENT(INOUT) :: NUM
  REAL, INTENT(INOUT) :: S
  INTEGER, INTENT(INOUT) :: LCN
  INTEGER, INTENT(INOUT) :: FND

  INTERFACE
    SUBROUTINE SEARCH(XTAB, NUM, S, LCN, FND)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !                                       N.C. STATE UNIVERSITY
      !
      !
      ! SEARCH CONDUCTS A BINARY SEARCH FOR S.  SEARCH IS CALLED ONLY IF S IS
      ! BETWEEN XTAB(1) AND XTAB(NUM).
      !
      ! ON INPUT--
      !
      !   XTAB CONTAINS THE ABSCISSAS OF THE DATA POINTS OF INTERPOLATION.
      !
      !   NUM IS THE DIMENSION OF XTAB.
      !
      !   S IS THE VALUE WHOSE RELATIVE POSITION IN XTAB IS LOCATED BY SEARCH.
      !
      !
      ! ON OUTPUT--
      !
      !   FND IS SET EQUAL TO 1 IF S IS FOUND IN XTAB AND IS SET EQUAL TO 0
      !   OTHERWISE.
      !
      !   LCN IS THE INDEX OF THE LARGEST VALUE IN XTAB FOR WHICH XTAB(I)
      !   .LT. S.
      !
      ! AND
      !
      !   SEARCH DOES NOT ALTER XTAB,NUM,S.
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT), DIMENSION(NUM) :: XTAB
      INTEGER, INTENT(INOUT) :: NUM
      REAL, INTENT(INOUT) :: S
      INTEGER, INTENT(INOUT) :: LCN
      INTEGER, INTENT(INOUT) :: FND
    END SUBROUTINE SEARCH
  END INTERFACE

  CALL SEARCH(XTAB, NUM, S, LCN, FND)
END SUBROUTINE C_SEARCH


SUBROUTINE C_CHOOSE(P1, P2, M1, M2, Q1, Q2, EPS, NCASE) BIND(C)
  IMPLICIT NONE
  REAL, INTENT(INOUT) :: P1
  REAL, INTENT(INOUT) :: P2
  REAL, INTENT(INOUT) :: M1
  REAL, INTENT(INOUT) :: M2
  REAL, INTENT(INOUT) :: Q1
  REAL, INTENT(INOUT) :: Q2
  REAL, INTENT(INOUT) :: EPS
  INTEGER, INTENT(INOUT) :: NCASE

  INTERFACE
    SUBROUTINE CHOOSE(P1, P2, M1, M2, Q1, Q2, EPS, NCASE)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !
      !
      ! CHOOSE DETERMINES THE CASE NEEDED FOR THE COMPUTATION OF THE PARAME-
      ! TERS OF THE QUADRATIC SPLINE AND RETURNS THE VALUE IN THE VARIABLE
      ! NCASE.
      !
      ! ON INPUT--
      !
      !   (P1,P2) GIVES THE COORDINATES OF ONE OF THE POINTS OF INTERPOLATION.
      !
      !   M1 SPECIFIES THE DERIVATIVE CONDITION AT (P1,P2).
      !
      !   (Q1,Q2) GIVES THE COORDINATES OF ONE OF THE POINTS OF INTERPOLATION.
      !
      !   M2 SPECIFIES THE DERIVATIVE CONDITION AT (Q1,Q2).
      !
      !   EPS IS AN ERROR TOLERANCE USED TO DISTINGUISH CASES WHEN M1 OR M2 IS
      !   RELATIVELY CLOSE TO THE SLOPE OR TWICE THE SLOPE OF THE LINE
      !   SEGMENT JOINING (P1,P2) AND (Q1,Q2).  IF EPS IS NOT EQUAL TO ZERO,
      !   THEN EPS SHOULD BE GREATER THAN OR EQUAL TO MACHINE EPSILON.
      !
      !
      ! ON OUTPUT--
      !
      !   NCASE CONTAINS THE VALUE WHICH CONTROLS HOW THE PARAMETERS OF THE
      !   QUADRATIC SPLINE ARE EVALUATED.
      !
      ! AND
      !
      !   CHOOSE DOES NOT ALTER P1,P2,Q1,Q2,M1,M2,EPS.
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT) :: P1
      REAL, INTENT(INOUT) :: P2
      REAL, INTENT(INOUT) :: M1
      REAL, INTENT(INOUT) :: M2
      REAL, INTENT(INOUT) :: Q1
      REAL, INTENT(INOUT) :: Q2
      REAL, INTENT(INOUT) :: EPS
      INTEGER, INTENT(INOUT) :: NCASE
    END SUBROUTINE CHOOSE
  END INTERFACE

  CALL CHOOSE(P1, P2, M1, M2, Q1, Q2, EPS, NCASE)
END SUBROUTINE C_CHOOSE


SUBROUTINE C_CASES(P1, P2, M1, M2, Q1, Q2, E1, E2, V1, V2, W1, W2, Z1, Z2, Y1, Y2, NCASE) BIND(C)
  IMPLICIT NONE
  REAL, INTENT(INOUT) :: P1
  REAL, INTENT(INOUT) :: P2
  REAL, INTENT(INOUT) :: M1
  REAL, INTENT(INOUT) :: M2
  REAL, INTENT(INOUT) :: Q1
  REAL, INTENT(INOUT) :: Q2
  REAL, INTENT(INOUT) :: E1
  REAL, INTENT(INOUT) :: E2
  REAL, INTENT(INOUT) :: V1
  REAL, INTENT(INOUT) :: V2
  REAL, INTENT(INOUT) :: W1
  REAL, INTENT(INOUT) :: W2
  REAL, INTENT(INOUT) :: Z1
  REAL, INTENT(INOUT) :: Z2
  REAL, INTENT(INOUT) :: Y1
  REAL, INTENT(INOUT) :: Y2
  INTEGER, INTENT(INOUT) :: NCASE

  INTERFACE
    SUBROUTINE CASES(P1, P2, M1, M2, Q1, Q2, E1, E2, V1, V2, W1, W2, Z1, Z2, Y1, Y2, NCASE)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !                                       N.C. STATE UNIVERSITY
      !
      !
      ! CASES COMPUTES THE KNOTS AND OTHER PARAMETERS OF THE SPLINE ON THE
      ! INTERVAL (P1,Q1).
      !
      !
      ! ON INPUT--
      !
      !   (P1,P2) AND (Q1,Q2) ARE THE COORDINATES OF THE POINTS OF
      !   INTERPOLATION.
      !
      !   M1 IS THE SLOPE AT (P1,P2).
      !
      !   M2 IS THE SLOPE AT (Q1,Q2)
      !
      !   NCASE CONTROLS THE NUMBER AND LOCATION OF THE KNOTS.
      !
      !
      ! ON OUTPUT--
      !
      !   (V1,V2),(W1,W2),(Z1,Z2), AND (E1,E2) ARE THE COORDINATES OF THE
      !   KNOTS AND OTHER PARAMETERS OF THE SPLINE ON (P1,Q1).  (E1,E2)
      !   AND (Y1,Y2) ARE USED ONLY IF NCASE=4.
      !
      ! AND
      !
      !   CASES DOES NOT ALTER P1,P2,M1,M2,Q1,Q2.
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT) :: P1
      REAL, INTENT(INOUT) :: P2
      REAL, INTENT(INOUT) :: M1
      REAL, INTENT(INOUT) :: M2
      REAL, INTENT(INOUT) :: Q1
      REAL, INTENT(INOUT) :: Q2
      REAL, INTENT(INOUT) :: E1
      REAL, INTENT(INOUT) :: E2
      REAL, INTENT(INOUT) :: V1
      REAL, INTENT(INOUT) :: V2
      REAL, INTENT(INOUT) :: W1
      REAL, INTENT(INOUT) :: W2
      REAL, INTENT(INOUT) :: Z1
      REAL, INTENT(INOUT) :: Z2
      REAL, INTENT(INOUT) :: Y1
      REAL, INTENT(INOUT) :: Y2
      INTEGER, INTENT(INOUT) :: NCASE
    END SUBROUTINE CASES
  END INTERFACE

  CALL CASES(P1, P2, M1, M2, Q1, Q2, E1, E2, V1, V2, W1, W2, Z1, Z2, Y1, Y2, NCASE)
END SUBROUTINE C_CASES


SUBROUTINE C_SPLINE(XVALS, Z1, Z2, XTABS, YTABS, XTABS1, YTABS1, Y1, Y2, E2, W2, V2, NCASE, SPLINE_RESULT) BIND(C)
  IMPLICIT NONE
  REAL, INTENT(INOUT) :: XVALS
  REAL, INTENT(INOUT) :: Z1
  REAL, INTENT(INOUT) :: Z2
  REAL, INTENT(INOUT) :: XTABS
  REAL, INTENT(INOUT) :: YTABS
  REAL, INTENT(INOUT) :: XTABS1
  REAL, INTENT(INOUT) :: YTABS1
  REAL, INTENT(INOUT) :: Y1
  REAL, INTENT(INOUT) :: Y2
  REAL, INTENT(INOUT) :: E2
  REAL, INTENT(INOUT) :: W2
  REAL, INTENT(INOUT) :: V2
  INTEGER, INTENT(INOUT) :: NCASE
  REAL :: SPLINE_RESULT

  INTERFACE
    FUNCTION SPLINE(XVALS, Z1, Z2, XTABS, YTABS, XTABS1, YTABS1, Y1, Y2, E2, W2, V2, NCASE)
      !
      !                                 SHAPE PRESERVING QUADRATIC SPLINES
      !                                   BY D.F.MCALLISTER & J.A.ROULIER
      !                                     CODED BY S.L.DODD & M.ROULIER
      !                                       N.C. STATE UNIVERSITY
      !
      !
      !   SPLINE FINDS THE IMAGE OF A POINT IN XVAL.
      !
      ! ON INPUT--
      !
      !   XVALS CONTAINS THE VALUE AT WHICH THE SPLINE IS EVALUATED.
      !
      !   (XTABS,YTABS) ARE THE COORDINATES OF THE LEFT-HAND DATA POINT
      !   USED IN THE EVALUATION OF XVALS.
      !
      !   (XTABS1,YTABS1) ARE THE COORDINATES OF THE RIGHT-HAND DATA POINT
      !   USED IN THE EVALUATION OF XVALS.
      !
      !   Z1,Z2,Y1,Y2,E2,W2,V2 ARE THE PARAMETERS OF THE SPLINE.
      !
      !   NCASE CONTROLS THE EVALUATION OF THE SPLINE BY INDICATING WHETHER
      !   ONE OR TWO KNOTS WERE PLACED IN THE INTERVAL (XTABS,XTABS1).
      !
      !
      ! ON OUTPUT--
      !
      !   SPLINE IS THE IMAGE OF XVALS.
      !
      ! AND
      !
      !   SPLINE DOES NOT ALTER ANY OF THE INPUT PARAMETERS.
      !
      !-----------------------------------------------------------------------
      IMPLICIT NONE
      REAL, INTENT(INOUT) :: XVALS
      REAL, INTENT(INOUT) :: Z1
      REAL, INTENT(INOUT) :: Z2
      REAL, INTENT(INOUT) :: XTABS
      REAL, INTENT(INOUT) :: YTABS
      REAL, INTENT(INOUT) :: XTABS1
      REAL, INTENT(INOUT) :: YTABS1
      REAL, INTENT(INOUT) :: Y1
      REAL, INTENT(INOUT) :: Y2
      REAL, INTENT(INOUT) :: E2
      REAL, INTENT(INOUT) :: W2
      REAL, INTENT(INOUT) :: V2
      INTEGER, INTENT(INOUT) :: NCASE
      REAL :: SPLINE
    END FUNCTION SPLINE
  END INTERFACE

  SPLINE_RESULT = SPLINE(XVALS, Z1, Z2, XTABS, YTABS, XTABS1, YTABS1, Y1, Y2, E2, W2, V2, NCASE)
END SUBROUTINE C_SPLINE

