PROGRAM TEST
USE LBFGS_MOD
IMPLICIT NONE
INTEGER, PARAMETER :: D = 10
REAL(KIND=R8) :: X(D)
REAL(KIND=R8), ALLOCATABLE :: HIST(:,:)
INTEGER :: IERR, I
X(:) = 1.0_R8

CALL LBFGS(D, QUAD_GRAD, X, IERR, HISTORY=HIST, EPS=EPSILON(0.0_R8)**2.0_R8)
IF (IERR .NE. 0) PRINT *, "ERROR : ", IERR

PRINT *, "X = ", X(:)

CONTAINS

SUBROUTINE QUAD_GRAD(X, G)
  REAL(KIND=R8), INTENT(IN) :: X(:)
  REAL(KIND=R8), INTENT(OUT) :: G(SIZE(X))
  REAL(KIND=R8) :: NOISE(SIZE(X))
  G(:) = 2.0_R8 * X(:)
  ! G(:) = 4.0_R8 * (X(:) ** 3.0_R8)
  ! G(:) = 6.0_R8 * (X(:) ** 5.0_R8)
  CALL RANDOM_NUMBER(NOISE(:))
  NOISE(:) = (NOISE(:) - .5_R8) * 2_R8
  G(:) = G(:) + .01_R8 * NOISE(:)
  RETURN
END SUBROUTINE QUAD_GRAD

END PROGRAM TEST
